### ISSUE TITLE
Error installing from .deb on elementaryOS (ubuntu 12.04)

### ISSUE THREAD

**Issue by opensas** [sialan-labs/sigram#1]
I just issued

```
sudo dpkg -i sigram_0.5.2-1-amd64.deb 
```

And I get the following error when trying to run it:

```
$ /opt/sialan/sigram/Sigram 
/opt/sialan/sigram/Sigram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /opt/sialan/sigram/Sigram)
/opt/sialan/sigram/Sigram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /opt/sialan/sigram/Sigram)
```

tested on elementaryOS luna

```
$ uname -a
Linux luna 3.2.0-64-generic #97-Ubuntu SMP Wed Jun 4 22:04:21 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Also tried with the tar.gz version, and got the following error:

```
$ ~/bin/sigram/Sigram 
/home/sas/bin/sigram/Sigram: error while loading shared libraries: libQt5Quick.so.5: cannot open shared object file: No such file or directory
```

**Comment by realbardia** [comment]
Hi...
We generated sigram packages on ubuntu 14.04. 
We will fix this problem soon.
Thank you for reporting.

**Comment by opensas** [comment]
Just to confirm, just tested it on ubuntu 14.04 and it worked like a charm (running it from the tar.gz gives me "This application failed to start because it could not find or load the Qt platform plugin "xcb")

**Comment by realbardia** [comment]
You should run tar package with run (shell script file) or before execute Sigram binary file you should set this environment variable:
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:<directory-path>/libs"

**Comment by opensas** [comment]
thanks, it worked great

**Comment by hotice** [comment]
The fix/work-around mentioned above works in Ubuntu 13.10 but not in Ubuntu 12.04 (tested in Ubuntu 12.04 64bit):

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /home/andrei/Downloads/sigram/Sigram)
/home/andrei/Downloads/sigram/Sigram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/andrei/Downloads/sigram/Sigram)
```

Ubuntu 12.04 uses libc6 version 2.15.

**Comment by hotice** [comment]
The Sigram debs would at least work in Ubuntu 13.10 (and 14.04) if they were built in Ubuntu 13.10... Possibly, if they are built in Ubuntu 12.04, they might work with all newer Ubuntu versions.

**Comment by realbardia** [comment]
I'm downloading Ubuntu 12.04 currently. When downloading finished, I'll create packages that works on older Linux too. (Maybe tonight or tomorrow morning)

**Comment by opensas** [comment]
great! just let us know so we can test it

**Comment by realbardia** [comment]
Packages updated. please check new packages. I compiled packages using 12.04.
http://labs.sialan.org/projects/sigram
