### ISSUE TITLE
Sigram does not start at Ubuntu Gnome 14.04

### ISSUE THREAD

**Issue by jonnius** [sialan-labs/sigram#105]
Sigram crashes at start with error message:

QQmlApplicationEngine failed to load component 
qrc:///main.qml:19 module "QtQuick" is not installed
qrc:///main.qml:20 module "QtQuick.Window" is not installed
qrc:///main.qml:19 module "QtQuick" is not installed
qrc:///main.qml:20 module "QtQuick.Window" is not installed

**Comment by WolfangAukang** [comment]
Try installing these:
sudo apt-get install qtdeclarative5-qtquick2-plugin
sudo apt-get install qtdeclarative5-window-plugin
