### ISSUE TITLE
QQmlApplicationEngine failed to load component

### ISSUE THREAD

**Issue by angelbladex** [sialan-labs/sigram#11]
Bad new: I installed sigram vía AUR on Archlinux ( https://github.com/sialan-labs/sigram/issues/4#issuecomment-45580343  ) and got

QQmlApplicationEngine failed to load component
qrc:///main.qml:21 module "QtGraphicalEffects" is not installed

God Notice:
the icon of sigram appear on systray (but crash if choose any option after got error) 

UPDATE: Sigram require qt5-graphicaleffects on Archlinux. i will report on AUR. 
Close this issue

**Comment by realbardia** [comment]
Thank you...
