### ISSUE TITLE
option for add contacts

### ISSUE THREAD

**Issue by angelbladex** [sialan-labs/sigram#12]
Sigram require a option for add contacts from application.

**Comment by realbardia** [comment]
This option exists on the core of the sigram. but not on UI. I hope we can add this feature to the UI soon.

**Comment by angelbladex** [comment]
Al least work for me. Don't forget add too option for change avatar profile.

**Comment by realbardia** [comment]
Changing avatar needs more times. But we will add this feature certainly.

**Comment by realbardia** [comment]
Added and pushed to github.
