### ISSUE TITLE
Add readme.md how compile 

### ISSUE THREAD

**Issue by angelbladex** [sialan-labs/sigram#2]
Readme.md required instructions for compile. ^_^

**Comment by realbardia** [comment]
Hi....
Yes :D I'll add it soon...

**Comment by Pablohn26** [comment]
For Fedora 20: 
--Install dependencies
yum install qt-creator qt5-qtbase qt5-qtbase-devel qt5-qtdeclarative qt5-qtquick1 qt5-qtquick1-devel kde-plasma-applicationname kde-plasma-nm qt5-qtdeclarative-devel qt5-qtdeclarative-static qt5-qtgraphicaleffects

--generate makefile
/bin/qmake-qt5 -o Makefile SialanTelegram.pro

--compile
make

--run
./SialanTelegram

**Comment by silberzwiebel** [comment]
Hey, followed your instructions, also on Fedora 20. Compilation works, but sigram won't start:

```
QQmlApplicationEngine failed to load component
qrc:///main.qml:149 Type ChatFrame unavailable
qrc:///ChatFrame.qml:40 Type ChatView unavailable
qrc:///ChatView.qml:415 Type UserConfig unavailable
qrc:///UserConfig.qml:246 Type ControlCombo unavailable
qrc:///ControlCombo.qml:2 module "QtQuick.Controls" version 1.2 is not installed
```

package `qt5-qtquickcontrols` is installed ...

**Comment by Pablohn26** [comment]
are qt5-qtquick1 and qt5-qtquick1-devel installed?

**Comment by realbardia** [comment]
What version of Qt installed? 5.0, 5.1, 5.2 or 5.3?

**Comment by silberzwiebel** [comment]
@Pablohn26 yes.
@realbardia seems to be 5.2.1

**Comment by Pablohn26** [comment]
Here I leave all the packages that I have installed (only in relation with qt5)
qt5-qtbase.x86_64  
qt5-qtbase-devel.x86_64  
qt5-qtbase-gui.x86_64  
qt5-qtbase-ibase.x86_64  
qt5-qtbase-mysql.x86_64  
qt5-qtbase-odbc.x86_64  
qt5-qtbase-postgresql.x86_64  
qt5-qtbase-tds.x86_64  
qt5-qtdeclarative.x86_64  
qt5-qtdeclarative-devel.x86_64  
qt5-qtdeclarative-static.x86_64 
qt5-qtgraphicaleffects.x86_64  
qt5-qtquick1.x86_64  
qt5-qtquick1-devel.x86_64  
qt5-qtquickcontrols.x86_64  
qt5-qtscript.x86_64  
qt5-qtscript-devel.x86_64  
qt5-qttools.x86_64  
qt5-qtwebkit.x86_64  
qt5-qtxmlpatterns.x86_64

**Comment by realbardia** [comment]
Ok... Qt 5.2 does now support QtQuick.Controls 1.2.
I changed QtQuick.Controls version to 1.0 and push it to git repository. You can pull it now.
I think it should fix problem.

**Comment by Pablohn26** [comment]
No problem here with 
Version     : 5.2.1
Release     : 1.fc20

**Comment by silberzwiebel** [comment]
Works for me now, thank you.
I have put the instructions in here to the README, so this issue can be closed.

**Comment by realbardia** [comment]
Thank you. I also add instructions for ubuntu.
