### ISSUE TITLE
Crash when switching connections

### ISSUE THREAD

**Issue by asoliverez** [sialan-labs/sigram#22]
I have an Ethernet and a wifi connection (with different routers).
When I switch from one to the other, sigram will crash.

I use networkmanager and kde 4.13. I'm usually on both Ethernet and wifi (with Ethernet being the main connection), but occasionally I have to wander off and disconnect the eth cable and then wifi becomes active. Then, sigram will silently shutdown. If I restart it, when I reconnect the eth cable, it will shutdown again.

I can try to get logs if needed. I use the 64-bit binaries in Opensuse 13.1

**Comment by realbardia** [comment]
I'm working on it and will fix it soon.
Thank you for reporting.

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
