### ISSUE TITLE
no icon under gnome-shell

### ISSUE THREAD

**Issue by silberzwiebel** [sialan-labs/sigram#23]
I don't see any icon when I use sigram under gnome-shell 3.12, Fedora 20. Neither a tray icon, nor any other icons.

Did I missed something while installing? I just compiled the newset source code with `make`

**Comment by ghost** [comment]
it works for me on gnome 3.12 on f20, cinnamon also works just in xfce i don't see a tray icon.

**Comment by silberzwiebel** [comment]
ok, somehow the tray icon appeared. I did this, not sure, what's the most important line here:

```
sudo yum reinstall librsvg2
sudo gtk-update-icon-cache
sudo gdk-pixbuf-query-loaders-32 --update-cache
sudo gdk-pixbuf-query-loaders-64 --update-cache
```

After that I restarted the GNOME Shell and saw the icon for the first time. So it seems not to be an issue of sigram, but of my GNOME setup.
