### ISSUE TITLE
Select own avatar not working

### ISSUE THREAD

**Issue by sl1pkn07** [sialan-labs/sigram#25]
hi

the select own avatar not working

steps
- go to options
- click in the avatar

test with latest git
Qt5 5.3.0

greetings

**Comment by angelbladex** [comment]
i have same problem. My case is different on #37 , i dont have profile avatar on other devices because i dont have smartphone

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
