### ISSUE TITLE
systray menu disappears when put cursor over the options

### ISSUE THREAD

**Issue by sl1pkn07** [sialan-labs/sigram#26]
hi

when open program menu in systray, this disappears when move the mouse over the options. only working if put cursor over "exit" option, if put cursor over "license" or the rest of options, the menu disappears

test with latest git
Qt5 5.3.0

greetings

**Comment by realbardia** [comment]
What distribution you use?

**Comment by sl1pkn07** [comment]
Archlinux & KDE

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
