### ISSUE TITLE
No StatusNofifier in KDE Systray

### ISSUE THREAD

**Issue by KAMiKAZOW** [sialan-labs/sigram#28]
Under KDE Plasma Sigram uses the traditional XEmbed-based tray icon, not a modern StatusNotifier one (StatusNotifier is the protocol used by Ubuntu under Unity as well).

**Comment by realbardia** [comment]
If you have libappindicator installed on your system, When you set DESKTOP_SESSION to ubuntu, sigram using unity tray icon system instead.
export DESKTOP_SESSION=ubuntu

**Comment by realbardia** [comment]
We will add some features to change system tray method in the future.
Thank you for reporting
