### ISSUE TITLE
sending file does not work with recently used files

### ISSUE THREAD

**Issue by silberzwiebel** [sialan-labs/sigram#34]
I tried to send a file to a group chat. I'm using GNOME shell 3.12. When picking the file under the "recently used" part of the file browser, sigram seems to do something (progress bar loads), but the file does not get send to the chat. When picking the same file by browsing to its location, the file gets published correctly.

**Comment by realbardia** [comment]
What is your linux distribution and system architecture? It's working on my system without problem :/

**Comment by silberzwiebel** [comment]
Ok, it works again for me. Don't know what was wrong...
