### ISSUE TITLE
Crash on Debian Jessie after entering code (Assertion '0' failed)

### ISSUE THREAD

**Issue by lotherk** [sialan-labs/sigram#35]
This happens to me on debian jessie with the ubuntu deb package and also the static linux binary (64bit versions)

It works well until I enter the confirmation code. After entering the code I get:

error #500: INTERDC_1_CALL_ERROR
sigram: ../sialan-telegram/telegram/telegram_cli/queries.c:608: fail_on_error: Assertion `0' failed.
[1]    10911 abort      sigram

**Comment by realbardia** [comment]
This error show when you entered wrong phone number or some thing like that.
I'll check it and fix it soon. thank you for reporting.

**Comment by lotherk** [comment]
Things I've entered were correct. The crash happend right after I've entered the confirmation code. I also did get a message to my telegram on the phone saying that a new client has been connected. 
Thanks for looking into this. Thanks for your work, I'm sure once it runs on my system I'll enjoy it alot. :-) :+1:

**Comment by lotherk** [comment]
It works when I compile sigram on my own, btw.

**Comment by lotherk** [comment]
Now that I've compiled it, I also can use the binary from the deb package (as I've authorized the computer with the own compiled version)
