### ISSUE TITLE
Crahs on Debian sid on system suspend restore

### ISSUE THREAD

**Issue by tglman** [sialan-labs/sigram#36]
After a suspend restore, operating on the window it make it crash !
from the log i get:

```
SialanTelegram: ../telegram/telegram_cli/mtproto-client.c:1654: process_rpc_message: Assertion `this_server_time >= st - 300 && this_server_time <= st + 30' failed.
Aborted (core dumped)
```

this is reproduced building from source on the master branch at the commit 8695964e7cb5665400d42010b4ed6ac3f4b3e836

may have to add an issue on telegram_cli?

**Comment by realbardia** [comment]
Yes... This is telegram_cli bug. telegram_cli had many bugs like this. when network connection deactived, changed, system suspend or ... .
We handled many of them on Sigram, but many others like this bug not handled yet.
Thank you for reporting.

**Comment by tglman** [comment]
just tried to compile the last one from here, this is not happening anymore on my environment, i consider it close !
Reopen it if in other environments is still happening
