### ISSUE TITLE
own profile picture is not shown

### ISSUE THREAD

**Issue by silberzwiebel** [sialan-labs/sigram#37]
sigram does not show my own profile picture. When I use another client, the picture is shown. My picture can also be seen by other users.

**Comment by realbardia** [comment]
Yes... We have some problems on telegram_cli part of the sigram that can't get own user info completely.
We will fix it soon.
Thank you for reporting.

**Comment by realbardia** [comment]
I made some changes on source. I think the profile picture downloads failed and sigram try to load corrupted file. I added some codes to remove corrupted files on start.
If not working please check YOUR_HOME/.config/sialan/telegram/downloads and check is there any corrupted file?
Thank you

**Comment by silberzwiebel** [comment]
It's not working for me. I don't see any corrupted files in the downloads folder...

**Comment by Choochmeque** [comment]
The main reason is:
void TelegramThread::_contactFounded(const UserClass &contact)

```
if( contact.flags & Enums::UserUserSelf )
    p->me = contact.user_id; <--- this never calls
```

So, I think, that's why your user info and avatar doesn't show.

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
