### ISSUE TITLE
check_phone_on_error: Assertion `0' failed.

### ISSUE THREAD

**Issue by cameri** [sialan-labs/sigram#39]
I'm getting the following error after typing my phone number and clicking the button to activate:

SialanTelegram: telegram/telegram_cli/queries.c:566: check_phone_on_error: Assertion `0' failed.
/usr/bin/sigram: line 3: 16147 Aborted                 (core dumped) ./SialanTelegram

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
