### ISSUE TITLE
undefined symbol: EVP_idea_cbc 

### ISSUE THREAD

**Issue by angelbladex** [sialan-labs/sigram#4]
I got this error
"... symbol lookup error: /usr/lib/libssl.so.1.0.0: undefined symbol: EVP_idea_cbc" after type ./run on ArchLinux 32 bits

Installed
openssl =>1.0.1.h-1
glibc ==> 2.19-5 

ldd Sigram | grep ssl
    libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0

**Comment by realbardia** [comment]
Thank you for reporting.
I'll check it and fix it soon.

**Comment by realbardia** [comment]
You can also install sigram from AUR until we fix the bug:
https://aur.archlinux.org/packages/sigram-git/

**Comment by angelbladex** [comment]
Hi @realbardia , i installed from AUR and i got this error on console, but prefer report other issue .
