### ISSUE TITLE
sigram segfaults after latest commit

### ISSUE THREAD

**Issue by silberzwiebel** [sialan-labs/sigram#41]
using your latest commit 2a16cd523132c79a9ee868f0864f5b7a1e18cb1f sigram doen'st start anymore. It gives a segfault.
Here is a run with gdb, let me know, if you need more info:

```
(gdb) run
[New Thread 0x7fffe37a3700 (LWP 3379)]
[New Thread 0x7fffd7730700 (LWP 3381)]
[New Thread 0x7fffd6857700 (LWP 3382)]
[New Thread 0x7fffd58d5700 (LWP 3383)]
[New Thread 0x7fffc4ce3700 (LWP 3384)]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
qrc:///Button.qml:61:25: Unable to assign QSizeF to QSize
[New Thread 0x7fffbffff700 (LWP 3385)]
[New Thread 0x7fffbf7fe700 (LWP 3386)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7730700 (LWP 3381)]
0x0000000000449d28 in get_contacts_on_answer (q=<optimized out>) at ../telegram/telegram_cli/queries.c:720
720   struct user U = user_chat_get(ourPeer(our_id))->user;
```

**Comment by TaylanTatli** [comment]
i installed sigram-git from aur. previously it was working now givin segfaults.

**Comment by realbardia** [comment]
Fixed

**Comment by TaylanTatli** [comment]
and now i can't install it. :/

Makefile:467: recipe for target 'copydeploymentfolders' failed
make[1]: **\* [copydeploymentfolders] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-doublet/aur-sigram-git/src/sigram-git-build/Sigram'
Makefile:38: recipe for target 'sub-Sigram-make_first-ordered' failed
make: **\* [sub-Sigram-make_first-ordered] Error 2

**Comment by cippaciong** [comment]
@TaylanTatli 
Look at https://github.com/sialan-labs/sigram/issues/43
I was able to create a working PKGBUILD and update the script in /usr/bin to start sigram. I already posted them on the AUR.
http://pastie.org/9342990
http://pastie.org/9342995

**Comment by realbardia** [comment]
Thank you for reporting. fixed...

**Comment by TaylanTatli** [comment]
Thank you i able to install with your pkgbuilds. :)
