### ISSUE TITLE
fail build: "make" target path same like source files

### ISSUE THREAD

**Issue by sl1pkn07** [sialan-labs/sigram#43]
log

http://sl1pkn07.no-ip.com/paste/view/1dd51849

with this "patch" solve the problem

sed -e "s/.target = ./.target = build/" -i Sigram/Sigram.pro

greetings

**Comment by cippaciong** [comment]
Seems to be related to https://github.com/sialan-labs/sigram/issues/41
By the way, I gave the workaround a try and it worked for me too.

**Comment by realbardia** [comment]
Thank you for reporting. fixed...
