### ISSUE TITLE
build 34e554b commit need tons off gnome/GTK2 stuff in KDE environment

### ISSUE THREAD

**Issue by sl1pkn07** [sialan-labs/sigram#44]
hi, 

build 34e554b1b06836104a458204b520b5b76e6504ce commit need a tons of gnome/gtk stuff in kde environment

http://sl1pkn07.no-ip.com/paste/view/997521ea

==> libappindicator dependencies:
- gobject-introspection (already installed)
- pygtk (already installed)
- perl-xml-libxml (already installed)
- dbus-glib (already installed)
- libindicator-gtk2 (building from AUR)
- libdbusmenu-gtk2 (building from AUR)
- vala (package found)
- gtk-sharp-2 (package found)

this is in Archlinux

is possible disable this in qmake/make flag?

greetings

**Comment by realbardia** [comment]
Currently no... But you can change "SUBDIRS += libs" Line from SialanTelegram.pro file to "//SUBDIRS += libs" to disable building appindicator module.

**Comment by sl1pkn07** [comment]
oks, thanks!
