### ISSUE TITLE
Instructions for compile failed: always compile for UnitySystemTray

### ISSUE THREAD

**Issue by angelbladex** [sialan-labs/sigram#46]
Hi!
Add support unity generated problems for Unity non-users. I tested compile without directory libs and work. 

![error](https://cloud.githubusercontent.com/assets/847922/3460249/37d80db8-0215-11e4-85c5-3f9c12cfcab2.png)

A possible solution is check if user use Unity , if dont use Unity , dont use directory libs.

Pd: I don't have update my installed version yet , but can show this image 
![20140702-164155](https://cloud.githubusercontent.com/assets/847922/3462473/d5b66d5a-022d-11e4-8a4c-d210dbe1c4df.jpg)
..and now, i can add contacts as reported in #12

**Comment by realbardia** [comment]
Yes... we should make smart build system that set unityplugins as optional.

**Comment by sl1pkn07** [comment]
related https://github.com/sialan-labs/sigram/issues/44 and fixed

**Comment by realbardia** [comment]
Fixed :)
