### ISSUE TITLE
Does not connect

### ISSUE THREAD

**Issue by jonnius** [sialan-labs/sigram#47]
I installed Sigram but it is just showing "Connecting" and nothing else happens. I even have not been asked for my phone number or something else.

**Comment by realbardia** [comment]
What is your linux distribution? and system architecture?

**Comment by jonnius** [comment]
Ubuntu Gnome 14.04, 64-bit.

**Comment by jonnius** [comment]
Does not appear any more

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
