### ISSUE TITLE
rsa_load_public_key: No such file or directory

### ISSUE THREAD

**Issue by tanwald** [sialan-labs/sigram#48]
When I try to launch the application I get the following:

$ /opt/Sigram/bin/Sigram 
rsa_load_public_key: No such file or directory
qthreadExitRequest 1 
Segmentation fault (core dumped)

Built with:
- 0204cc6 Change build steps & 80eb4e1 0.5.5.2 Version
- 3.14.9-200.fc20.x86_64

**Comment by realbardia** [comment]
There is a file in the source tree. tg-server.pub
Copy this file in the binary directory
