### ISSUE TITLE
Where are the translation files in the source?

### ISSUE THREAD

**Issue by edu791** [sialan-labs/sigram#5]
I'd like to help on the Spanish translation, but I don't know where are the translation strings files.

**Comment by realbardia** [comment]
We are working on translation system. tonight or tomorrow we will release a version that support translations.

**Comment by Pablohn26** [comment]
I would suggest transifex.com :)

**Comment by realbardia** [comment]
Thank you :)

**Comment by realbardia** [comment]
Translations feature added. You can find files on the https://github.com/sialan-labs/sigram/tree/master/translations_sources and edit translation with qt linguist application.
