### ISSUE TITLE
'fi' is not printed

### ISSUE THREAD

**Issue by silberzwiebel** [sialan-labs/sigram#51]
see screenshot:

![auswahl_015](https://cloud.githubusercontent.com/assets/4533862/3540907/893700f0-0847-11e4-8e0b-5f940b29f581.png)

since I know it is correct in the translation file, it seems some graphical issue...

**Comment by realbardia** [comment]
Yes... This is render bug. I think it is qt5 bug.

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
