### ISSUE TITLE
Cannot type Persian in Sigram!

### ISSUE THREAD

**Issue by hedayat** [sialan-labs/sigram#54]
Hi!
Thank you for this application. I tried it under Gnome shell. I am able to successfully log-in into Telegram, but I cannot type in Persian in it. I do change my keyboard layout to Persian, and I can type in Persian in other applications but in Sigram, it always types in English while the keyboard indicator shows 'fa' as the active keyboard layout.

Thanks again

**Comment by hedayat** [comment]
I forgot to mention that I'm using Gnome Shell 3.10 under Fedora 20, which uses IBus for input. It is really weird to see this happens! I wonder what is wrong.

**Comment by realbardia** [comment]
Hi...
There was a bug like this between Qt5 or IBus on some systems. Please check another Qt5 applications like QtCreator or Viber.
I think it is Qt5 or IBus bug.

**Comment by hedayat** [comment]
Oops, yes you are right. I tried another Qt5 QML application and faced the same issue. :(

**Comment by hedayat** [comment]
Well, I updated to Qt 3.5.1 and now the issue is fixed! :P 

A side note (sorry that it is not related to this topic): it is really weird that qt-creator is listed as a dependency for siagram compilation on Fedora. I'm almost sure that qt-creator does not contain anything needed to compile Qt applications. (And actually, qt-creator in Fedora 20 is compiled against Qt4 rather than Qt5).

**Comment by realbardia** [comment]
It's good...

Aw!!!
Thank you for reporting. Yes it's not compile dependency.
Fixed :)
