### ISSUE TITLE
Feature Request: Please add RightToLeft text support

### ISSUE THREAD

**Issue by hedayat** [sialan-labs/sigram#56]
Currently Sigram doesn't support showing RTL sent/received messages (It shows them in LTR direction). It would be nice if Sigram shows RTL texts in RTL (it already works in message compose box where we type our own messages).

**Comment by realbardia** [comment]
Qt and Qml objects supports RTL and LTR by default.
Maybe I did something wrong in the source code. I will fix it soon.
Thank you for reporting.

**Comment by realbardia** [comment]
Fixed :)
