### ISSUE TITLE
Sigram Crashed

### ISSUE THREAD

**Issue by hedayat** [sialan-labs/sigram#57]
I used Sigram for some time and it has crashed twice while I was typing (in Persian) and at the same time I was receiving some texts in a group chat. Sigram crashed with this assertion failure:

Sigram: telegram/telegram_cli/mtproto-client.c:1630: process_rpc_message: Assertion `!(enc->msg_len & 3) && enc->msg_len > 0 && enc->msg_len <= len - MINSZ && len - MINSZ - enc->msg_len <= 12' failed.

**Comment by realbardia** [comment]
I think it is telegram_cli project bug. Anyway I will check and try to fix it.
We will porting to libqtelegram libraries that is different from telegram_cli. It will fix many of sigram bugs.

**Comment by hedayat** [comment]
Have you tried anything to fix this issue? I have not seen this problem recently (I'm using the git version).

**Comment by realbardia** [comment]
No... I dont know why. But maybe a system update fixed this bugs...

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
