### ISSUE TITLE
Can't run on Fedora 20

### ISSUE THREAD

**Issue by rafaelmr2** [sialan-labs/sigram#6]
Fedora uses libcrypto.so.1.0.1e, I created a link libcrypto.so.1.0.0. I installed the package qt5-qtdeclarative. When I tried to run Sigram I had the message : 

```
./Sigram: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./Sigram)
```

**Comment by Pablohn26** [comment]
I have not had problems with it. 
ls /lib64/libcrypto*
libcryptopp.so.6      libcryptopp.so.6.0.0  libcrypto.so          libcrypto.so.10       libcrypto.so.1.0.1e

**Comment by rafaelmr2** [comment]
I tried with "./run" and not "./Sigram" and works. Sorry about this! :P
