### ISSUE TITLE
Hotkeys in non Latin layout

### ISSUE THREAD

**Issue by oromay** [sialan-labs/sigram#61]
To help you to improve this already very nice app I would like to report that hotkeys (ctrl + c/v/a, etc) are not working while typing in Russian. My system is ubuntu 14.04, 64.

**Comment by realbardia** [comment]
Thank you.
I think it is Qt5 bug. Shortcut keys are not working on another Qt5 apps.
Thank you for reporting.
Anyway, We'll try to fix it in another way.

**Comment by realbardia** [comment]
https://bugs.launchpad.net/ubuntu/+bug/1299474
This is the bug on launchpad.
