### ISSUE TITLE
MD5 Checksum Failed when Installing through Ubuntu Software Center

### ISSUE THREAD

**Issue by luisalvarado** [sialan-labs/sigram#62]
Using version sigram_0.6.2-1-amd64 when I try to install it (GUI Style) through the Ubuntu Software Center on Ubntu 14.04.1 I get the following:

![screenshot from 2014-08-04 09 57 50](https://cloud.githubusercontent.com/assets/29236/3799716/62703f7e-1bf0-11e4-8725-4306e1955198.png)

It is possible to avoid the warning through the terminal but this will look like a security problem or package is corrupted problem.

**Comment by realbardia** [comment]
Yes... last package of sigram has some problems.
We will fix it in the next version.
Thank you for reporting.

**Comment by realbardia** [comment]
Fixed
