### ISSUE TITLE
Not showing text on settings window

### ISSUE THREAD

**Issue by varlesh** [sialan-labs/sigram#65]
In Russian translate not show in settings window, but other windows show text. 
Other locales show text in settings window and other windows.
Maybe I made ​​a mistake somewhere?
Ubuntu 14.04 Unity
![2014-08-10 14 16 46](https://cloud.githubusercontent.com/assets/8083855/3869024/fa2172bc-2077-11e4-8946-8b9286ffc84c.png)
And error:

``` xml
<source>Start Secret Chat (not working yet, we working on it)</source>
<translation>Приватный чат (пока не не функионирует, мы работаем над этим)</translation>
 <source>Start Secret Chat (not working yet, we working on it)</source>
<translation>Приватный чат (пока не функионирует, мы работаем над этим)</translation>

```

**Comment by realbardia** [comment]
Thank you for reporting.
We'll fix it soon.

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)

**Comment by varlesh** [comment]
Thx :+1: )
