### ISSUE TITLE
[Bug]: Impossible to send files with space in filename

### ISSUE THREAD

**Issue by Choochmeque** [sialan-labs/sigram#70]
Steps to reproduce:
- Select file with space in filename (i.e. Star Track.mp4) and send it.

Obtained result: Nothing happens.

P.S.
Pls, assign this issue on me =)/

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
