### ISSUE TITLE
fedora 20 , failed nv-glx and nouveau .. 

### ISSUE THREAD

**Issue by eskuai** [sialan-labs/sigram#76]
Hello,

Trying to run Sigram, all process was ok, but failed to run 
I am not installed nvidia drivers... nouveau instead ... 

darkstar build]$ ./Sigram 
Xlib:  extension "NV-GLX" missing on display ":0.0".
Xlib:  extension "NV-GLX" missing on display ":0.0".
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Xlib:  extension "NV-GLX" missing on display ":0.0".
Xlib:  extension "NV-GLX" missing on display ":0.0".
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
Sigram: xcb_io.c:736: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
Aborted
[jsanz@darkstar build]$ locate libglx.so
/usr/lib/xorg/modules/extensions/libglx.so
/usr/lib/xorg/modules/extensions/libglx.so.280.13

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
