### ISSUE TITLE
Tray Icon in Unity at wrong place

### ISSUE THREAD

**Issue by jonnius** [sialan-labs/sigram#78]
With Ubuntu Unity the tray icon is overlaying the window buttons instead of beeing displayed in the notification area as shown in the attached picture.

![sigram problem](https://cloud.githubusercontent.com/assets/4456588/4481488/71426dd2-49a0-11e4-806a-ed5c0d907c2c.png)

**Comment by realbardia** [comment]
Hi
What is version of ubuntu, you use? Please check libappindicator1 package is installed or not?
Also please check, UnitySystemTray plugin is loaded or not?
cat /proc/[Sigram PID]/maps | grep UnitySystemTray
Thank you...

**Comment by jonnius** [comment]
It is Ubuntu 14.04. Installing libappindicator1 solved the problem. Thanks!
