### ISSUE TITLE
Bug: execution symbolic links

### ISSUE THREAD

**Issue by rhoconlinux** [sialan-labs/sigram#8]
In addition to the executing permissions (unavoidable fix in order to make it work) you also may need to add some symbolic links to the bin folder in order to make the launcher work. 
After adding execution permissions to Sigram, you can do this to make it work out-of-the-box. 
<code>
sudo ln -s /opt/sialan/sigram/Sigram /usr/bin/ && sudo ln -s /usr/bin/Sigram /usr/bin/sigram
</code>
Cheers.

**Comment by realbardia** [comment]
Thank you... We will adding this symlinks on the next binary packages.

**Comment by realbardia** [comment]
Symlinks added to last binary packages (0.5.5).
Thank you :)
