### ISSUE TITLE
Sigram integration with kfilechoser and gnome-filechoser

### ISSUE THREAD

**Issue by sergioad** [sialan-labs/sigram#80]
Hello all the Sigram and Sialam labs team I am here to ask you add kfilechoser / gnome-filechoser integration with Sigram to make the file uploads more confortable and native to your used desktop, Also this will make Sigram better if it is posible I will like see it on the next release,

**Comment by realbardia** [comment]
Hello
It's good idea. We'll try to add kfilechooser and gnome-filechooser support to sigram in the next releases.
Thank you

**Comment by sergioad** [comment]
Thanks to you :)

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
