### ISSUE TITLE
Connection problems after connection was quit by other device

### ISSUE THREAD

**Issue by jonnius** [sialan-labs/sigram#82]
If I quit all connections from my phone, Sigram won't react properly when startet the next time. It should recognize this and ask for the phone number again for authentification. But it just tries to connect forever.

**Comment by jonnius** [comment]
A workaround is to delete sialan folder (~/.config/sialan) and reboot computer (why that?!).

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)
