### ISSUE TITLE
[BUG] Images sent in group are set as avatar image

### ISSUE THREAD

**Issue by ghost** [sialan-labs/sigram#87]
Hello.

When someone in a group send an image is set as avatar image for other contacts who hasn't any avatar.

**Comment by realbardia** [comment]
Hi
Yes... I saw this bug. this telegram-cli bug.
We are porting sigram to libqtelegram from telegram-cli. I hope it will fix bugs like this.
Thank you for reporting.

**Comment by ghost** [comment]
Thank you for replying

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)

**Comment by ghost** [comment]
Thank you so much. You're awesome.
