### ISSUE TITLE
Gear button does nothing

### ISSUE THREAD

**Issue by hotice** [sialan-labs/sigram#9]
In a chat, there's a gear icon/button in the top right corner. What is that button supposed to do? Because currently it doesn't do anything when clicked for me.

Tested in Ubuntu 14.04 64bit.

**Comment by realbardia** [comment]
It should showing configure dialog. But I don't know why it doesn't work on some systems!
Anyway We are working on it. thank you for reporting.

**Comment by realbardia** [comment]
Bug fixed on git repository and on binary packages soon.
