### ISSUE TITLE
crash on startup ubuntu gnome 14.10

### ISSUE THREAD

**Issue by midi** [sialan-labs/sigram#90]
sigram crashes for me under 14.10.

when i start it, i see an invisible tray icon then i click right and select show, then the invisible icon disappears.

do you need logs, how can i get them?

**Comment by realbardia** [comment]
Hi
Yes... Please send me console output.
Thank you

**Comment by midi** [comment]
Nov 11 22:00:58 machine kernel: [11795.279786] Sigram[12892]: segfault at 8 ip 00007f62729e6490 sp 00007fffaaa0d4c0 error 4 in libQt5Gui.so.5.3.0[7f62728fc000+513000]
Nov 11 22:01:55 machine kernel: [11852.554232] sigram[14202]: segfault at 28 ip 00007f907100d490 sp 00007fff55b99a30 error 4 in libQt5Gui.so.5.3.0[7f9070f23000+513000]

is this enough, or do you want the .crash file?

**Comment by realbardia** [comment]
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)

**Comment by midi** [comment]
when will get one branch get pushed to the ppa?

thank you!
