### ISSUE TITLE
Sigram uses proprietary emojis

### ISSUE THREAD

**Issue by Lazza** [sialan-labs/sigram#92]
Currently Sigram uses the proprietary Apple font to display emoji characters. The license is unclear, but it should be considered proprietary unless proven otherwise. Fortunately, some days ago Twitter decided to open source their emojis collection: https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone

I would like to suggest the switch to this set of open source emojis instead of the Apple font.

By the way, they look pretty well, I would say even sharper than the Apple ones:

![Imgur](http://i.imgur.com/0nV1qYl.png)

**Comment by dottorblaster** [comment]
Definitely upvote for this, way better than blurry Applish emojis.

**Comment by ghost** [comment]
I like the idea and I think the Twitter emojis fit better in Sigram's desing

**Comment by sergioad** [comment]
Or using the Google emojis?

**Comment by KAMiKAZOW** [comment]
Why does an application ship its own Emoji anyway? Emoji are just Unicode characters that should be provided by the system's fonts. IMO Sigram's package should just require "gdouros-symbola-fonts". End of story.

**Comment by Lazza** [comment]
Linux does not support colored fonts. You can use Google's black and white emojis or Symbola, but both are inadequate. Those in Symbola, especially, are quite ugly so not an option.

**Comment by KAMiKAZOW** [comment]
Then fix FreeType to support color emoji and whatever users find an option is up to them.

**Comment by realbardia** [comment]
Thanks for this suggestion. This emoticons is so beautiful.
Sigram support emojis theme in the base currently. Just I should make a good user interface and menu for this feature.
I will add twitter emoticons and another emoticons theme in the next version. (Soon)
Thank you :)

**Comment by Lazza** [comment]
That's great, thanks. :smile: Does it mean that they will be added along the Apple ones, or will they replace those? Regarding the Apple emojis, did Apple authorize their use into Sigram?

Another (small) caveat is that some Twitter emojis, such as :curly_loop:, use precisely the same gray color as the background of the emojis menu. I think you should change it a little bit.

**Comment by realbardia** [comment]
Twitter emoji added to Sigram-One branch. Also apple emoji removed from project and Twitter emoji is our default emoji icons now.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)

**Comment by dottorblaster** [comment]
This is A-MA-ZING @realbardia, thank you for your support and for this great news! \o/

**Comment by Lazza** [comment]
This is awesome! :smile: Thank you @realbardia.
