### ISSUE TITLE
Sigram-one fail build

### ISSUE THREAD

**Issue by sl1pkn07** [sialan-labs/sigram#97]
g++ -c -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE -DSIALAN_NOTIFICATION -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I../../Sigram -isystem /usr/include/libqtelegram -isystem /usr/include/qt -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I/home/sl1pkn07/aplicaciones/sigram-git/src/sigram/build/Sigram -I. -o telegramqml.o ../../Sigram/telegramqml.cpp
In file included from ../../Sigram/telegramqml.cpp:22:0:
../../Sigram/objects/types.h:12:25: fatal error: types/types.h: No such file or directory
 #include <types/types.h>
                         ^
compilation terminated.

greetings

**Comment by realbardia** [comment]
Hi
You should build and install libqtelegram before building sigram.
`bzr branch lp:libqtelegram`
`cd libqtelegram`
`./build.sh`
`cd build && make install`

**Comment by sl1pkn07** [comment]
where i can get the module "thumbnailer" for build libqtelegram?

greetings

**Comment by realbardia** [comment]
libthumbnailer-dev and libmediainfo-dev packages.
If you are using ubuntu, install it using this command:
`sudo apt-get install libthumbnailer-dev`
and for mediainfo:
`sudo apt-get install libmediainfo-dev`

**Comment by sl1pkn07** [comment]
the problem is I not use ubuntu, use arch

thanks for the info

greetings

2014-11-24 21:18 GMT+01:00 Bardia notifications@github.com:

**Comment by sl1pkn07** [comment]
sigh, thumbnailer use gstreamer

I'll leave the project

thanks for all
