### ISSUE TITLE
Sigram-one fail build problem

### ISSUE THREAD

**Issue by Ex2nd** [sialan-labs/sigram#99]
Hi

I tried to build Sigram One, but I got an error. Not prompt in what could be the problem. I also installed the library libqtelegram. 

/Sigram/telegramqml.cpp:575: error: no matching function for call to 'Telegram::messagesSendMessage(InputPeer&, const QString&)'
     qint64 sendId = p->telegram->messagesSendMessage(peer, msg);
                                                               ^

/Sigram/telegramqml.cpp:641: error: no matching function for call to 'Telegram::messagesSendPhoto(InputPeer&, QString&)'
         fileId = p->telegram->messagesSendPhoto(peer, file);
                                                           ^

/Sigram/telegramqml.cpp:644: error: no matching function for call to 'Telegram::messagesSendVideo(InputPeer&, QString&, int, int, int)'
         fileId = p->telegram->messagesSendVideo(peer, file, 0, 0, 0);
                                                                    ^
/Sigram/telegramqml.cpp:647: error: no matching function for call to 'Telegram::messagesSendAudio(InputPeer&, QString&, int)'
         fileId = p->telegram->messagesSendAudio(peer, file, 0);
                                                              ^
p.s: Can I try somewhere Sigram One? I see you stopped supporting Sigram.

**Comment by realbardia** [comment]
Hi...
It's because libqtelegram api changed.
Sigram updated now. you can pull last commits and build again.
Sigram One is next version of Sigram. It will release soon :)
